project:
  type: website
  output-dir: docs

website:
  site-url: https://arsenelaurent.github.io/
  title: "ArseneLaurent"
  navbar:
    left:
      - text: Projects
        menu:
         - text: Home
           href: index.qmd
         - text: Netflix Analysis
           href: ds002_project2.qmd
         - text: Blackjack Simulation
           href: ds002_project3.qmd
         - text: Ethics of AI in the Hiring Process
           href: Project_4.qmd
         - text: Traffic Stops by Race in FL, OR, and WA
           href: Project_5.qmd
      - text: Blackjack Simulation Presentation
        href: Blackjack_Simulation_Presentation.qmd
    right: 
      - text: "Data Viz"
        menu: 
         - text: "London Marathon"
           href: LondonMarathon.qmd
         - text: "Chocolate Ratings"
           href: ChocolateRatings.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: source

