project:
  type: website
  output-dir: docs

website:
  site-url: https://arsenelaurent.github.io/
  title: "ArseneLaurent"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Mini-Project 2
        href: ds002_project2.qmd
      - text: Project 3
        href: ds002_project3.qmd
    right: 
      - text: "Data Viz"
        menu: 
         - text: "London Marathon"
           href: LondonMarathon.html
         - text: "Chocolate Ratings"
           href: ChocolateRatings.html

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: source

